start_url: "https://www.wyseguys.com/"
allowed_hosts:
  - "www.wyseguys.com"
output_dir: "./output"
log_dir: "./logs"
db_path: "./crawl.db"
log_level: "debug"
http_timeout: 10
concurrency: 1
rate_ms: 2000